name: 'Build, test and deploy to testing environment on pull request'

on:
  pull_request:


env:
  AZURE_RESOURCE_GROUP: DevOps
  AZURE_APP_PLAN: ChatApp

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      packages: write

    steps:

      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Build jar (running Checkstyle and unit tests) and generate jacoco test report
      - name: Generate jacoco test report and build jar
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport
          ./gradlew build

      # Add coverage based on report xml to pull request
      - name: Add coverage to pull request
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80

      # Log in to ghcr.io
      - name: Log in to ghcr.io
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get image name with tag from metadata-action (tag will be :pr-<pr-number>)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      # Build and push Docker image to ghcr.io using image name and tag from metadata-action
      - name: Build and push Docker image to ghcr.io
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Run image locally to run integration tests in next step
      - name: Run image
        run: |
          docker run -d -p 8080:8080 ${{ steps.meta.outputs.tags }}

      # Run integration tests against running image
      - name: Run integration tests
        run: |
          ./gradlew integrationTest

      # Log in to Azure
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure Web App using Azure CLI with image from ghcr.io
      - name: Deploy Azure Web App with ghcr container image
        run: |
          deployment_name="test-deployment-${{ github.head_ref || github.ref_name }}"
          az webapp create --name $deployment_name --resource-group $AZURE_RESOURCE_GROUP --plan $AZURE_APP_PLAN -i ${{ steps.meta.outputs.tags }} -w ${{ secrets.GITHUB_TOKEN }} -s ${{ github.actor }}
          webapp_url=$(az webapp show --name $deployment_name --resource-group $AZURE_RESOURCE_GROUP --query defaultHostName -o tsv)
          echo "### :mag: Test deployment available at [$webapp_url](https://$webapp_url)" > webappurl.txt

      # Add test deployment url to pull request using url written to txt file in previous step
      - name: Add test deployment url to pull request
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: webappurl.txt